data_processing:
  remove_misc: true
  split_data: timeseries # random
input: merchant_only
category: primary
model: mini

classifier:
  name: nearest_neighbors
  options:
    n_neighbors: 10
    metric: cosine
